'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Task
    Public Property id As Integer
    Public Property Description As String
    Public Property DueDate As Nullable(Of Date)
    Public Property Priority As Nullable(Of Byte)
    Public Property Criticality As String
    Public Property CategoryId As Nullable(Of Integer)

    Public Overridable Property Category As Category

End Class
